//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OpenposeRos2
{
    [Serializable]
    public class PoseKeyPointsMsg : Message
    {
        public const string k_RosMessageName = "openpose_ros2_msgs/PoseKeyPoints";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public PoseKeyPointMsg[] pose_key_points;

        public PoseKeyPointsMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pose_key_points = new PoseKeyPointMsg[0];
        }

        public PoseKeyPointsMsg(Std.HeaderMsg header, PoseKeyPointMsg[] pose_key_points)
        {
            this.header = header;
            this.pose_key_points = pose_key_points;
        }

        public static PoseKeyPointsMsg Deserialize(MessageDeserializer deserializer) => new PoseKeyPointsMsg(deserializer);

        private PoseKeyPointsMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pose_key_points, PoseKeyPointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.pose_key_points);
            serializer.Write(this.pose_key_points);
        }

        public override string ToString()
        {
            return "PoseKeyPointsMsg: " +
            "\nheader: " + header.ToString() +
            "\npose_key_points: " + System.String.Join(", ", pose_key_points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
