//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OpenposeRos2
{
    [Serializable]
    public class PoseKeyPointsListMsg : Message
    {
        public const string k_RosMessageName = "openpose_ros2_msgs/PoseKeyPointsList";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public PoseKeyPointsMsg[] pose_key_points_list;

        public PoseKeyPointsListMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pose_key_points_list = new PoseKeyPointsMsg[0];
        }

        public PoseKeyPointsListMsg(Std.HeaderMsg header, PoseKeyPointsMsg[] pose_key_points_list)
        {
            this.header = header;
            this.pose_key_points_list = pose_key_points_list;
        }

        public static PoseKeyPointsListMsg Deserialize(MessageDeserializer deserializer) => new PoseKeyPointsListMsg(deserializer);

        private PoseKeyPointsListMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.pose_key_points_list, PoseKeyPointsMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.pose_key_points_list);
            serializer.Write(this.pose_key_points_list);
        }

        public override string ToString()
        {
            return "PoseKeyPointsListMsg: " +
            "\nheader: " + header.ToString() +
            "\npose_key_points_list: " + System.String.Join(", ", pose_key_points_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
