//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OpenposeRos2
{
    [Serializable]
    public class PoseKeyPointMsg : Message
    {
        public const string k_RosMessageName = "openpose_ros2_msgs/PoseKeyPoint";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;
        public float score;

        public PoseKeyPointMsg()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.score = 0.0f;
        }

        public PoseKeyPointMsg(float x, float y, float z, float score)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.score = score;
        }

        public static PoseKeyPointMsg Deserialize(MessageDeserializer deserializer) => new PoseKeyPointMsg(deserializer);

        private PoseKeyPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.score);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.score);
        }

        public override string ToString()
        {
            return "PoseKeyPointMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nscore: " + score.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
