//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class AddThreeIntsRequest : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/AddThreeInts";
        public override string RosMessageName => k_RosMessageName;

        public long a;
        public long b;
        public long c;

        public AddThreeIntsRequest()
        {
            this.a = 0;
            this.b = 0;
            this.c = 0;
        }

        public AddThreeIntsRequest(long a, long b, long c)
        {
            this.a = a;
            this.b = b;
            this.c = c;
        }

        public static AddThreeIntsRequest Deserialize(MessageDeserializer deserializer) => new AddThreeIntsRequest(deserializer);

        private AddThreeIntsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.a);
            deserializer.Read(out this.b);
            deserializer.Read(out this.c);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a);
            serializer.Write(this.b);
            serializer.Write(this.c);
        }

        public override string ToString()
        {
            return "AddThreeIntsRequest: " +
            "\na: " + a.ToString() +
            "\nb: " + b.ToString() +
            "\nc: " + c.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
