//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class AddThreeIntsResponse : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/AddThreeInts";
        public override string RosMessageName => k_RosMessageName;

        public long sum;

        public AddThreeIntsResponse()
        {
            this.sum = 0;
        }

        public AddThreeIntsResponse(long sum)
        {
            this.sum = sum;
        }

        public static AddThreeIntsResponse Deserialize(MessageDeserializer deserializer) => new AddThreeIntsResponse(deserializer);

        private AddThreeIntsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sum);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sum);
        }

        public override string ToString()
        {
            return "AddThreeIntsResponse: " +
            "\nsum: " + sum.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
