//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class PlanExcutionRequest : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/PlanExcution";
        public override string RosMessageName => k_RosMessageName;

        public long index;
        public string name;

        public PlanExcutionRequest()
        {
            this.index = 0;
            this.name = "";
        }

        public PlanExcutionRequest(long index, string name)
        {
            this.index = index;
            this.name = name;
        }

        public static PlanExcutionRequest Deserialize(MessageDeserializer deserializer) => new PlanExcutionRequest(deserializer);

        private PlanExcutionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "PlanExcutionRequest: " +
            "\nindex: " + index.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
