//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class SpawnRizonVisualResponse : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/SpawnRizonVisual";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public SpawnRizonVisualResponse()
        {
            this.success = false;
        }

        public SpawnRizonVisualResponse(bool success)
        {
            this.success = success;
        }

        public static SpawnRizonVisualResponse Deserialize(MessageDeserializer deserializer) => new SpawnRizonVisualResponse(deserializer);

        private SpawnRizonVisualResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "SpawnRizonVisualResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
