//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class SpawnRizonVisualRequest : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/SpawnRizonVisual";
        public override string RosMessageName => k_RosMessageName;

        public double[] joint_state;

        public SpawnRizonVisualRequest()
        {
            this.joint_state = new double[7];
        }

        public SpawnRizonVisualRequest(double[] joint_state)
        {
            this.joint_state = joint_state;
        }

        public static SpawnRizonVisualRequest Deserialize(MessageDeserializer deserializer) => new SpawnRizonVisualRequest(deserializer);

        private SpawnRizonVisualRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_state, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_state);
        }

        public override string ToString()
        {
            return "SpawnRizonVisualRequest: " +
            "\njoint_state: " + System.String.Join(", ", joint_state.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
