//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class DigitalInputMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/DigitalInput";
        public override string RosMessageName => k_RosMessageName;

        public DigitalStateMsg[] digital_input;

        public DigitalInputMsg()
        {
            this.digital_input = new DigitalStateMsg[16];
        }

        public DigitalInputMsg(DigitalStateMsg[] digital_input)
        {
            this.digital_input = digital_input;
        }

        public static DigitalInputMsg Deserialize(MessageDeserializer deserializer) => new DigitalInputMsg(deserializer);

        private DigitalInputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.digital_input, DigitalStateMsg.Deserialize, 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.digital_input);
        }

        public override string ToString()
        {
            return "DigitalInputMsg: " +
            "\ndigital_input: " + System.String.Join(", ", digital_input.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
