//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class DigitalOutputMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/DigitalOutput";
        public override string RosMessageName => k_RosMessageName;

        public DigitalStateMsg[] digital_output;

        public DigitalOutputMsg()
        {
            this.digital_output = new DigitalStateMsg[0];
        }

        public DigitalOutputMsg(DigitalStateMsg[] digital_output)
        {
            this.digital_output = digital_output;
        }

        public static DigitalOutputMsg Deserialize(MessageDeserializer deserializer) => new DigitalOutputMsg(deserializer);

        private DigitalOutputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.digital_output, DigitalStateMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.digital_output);
            serializer.Write(this.digital_output);
        }

        public override string ToString()
        {
            return "DigitalOutputMsg: " +
            "\ndigital_output: " + System.String.Join(", ", digital_output.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
