//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class DigitalStateMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/DigitalState";
        public override string RosMessageName => k_RosMessageName;

        public uint pin;
        public bool state;

        public DigitalStateMsg()
        {
            this.pin = 0;
            this.state = false;
        }

        public DigitalStateMsg(uint pin, bool state)
        {
            this.pin = pin;
            this.state = state;
        }

        public static DigitalStateMsg Deserialize(MessageDeserializer deserializer) => new DigitalStateMsg(deserializer);

        private DigitalStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pin);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pin);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "DigitalStateMsg: " +
            "\npin: " + pin.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
