//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class FramePoseMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/FramePose";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public double[] data;

        public FramePoseMsg()
        {
            this.name = "";
            this.data = new double[7];
        }

        public FramePoseMsg(string name, double[] data)
        {
            this.name = name;
            this.data = data;
        }

        public static FramePoseMsg Deserialize(MessageDeserializer deserializer) => new FramePoseMsg(deserializer);

        private FramePoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.data, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "FramePoseMsg: " +
            "\nname: " + name.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
