//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class HanoiGrabMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/HanoiGrab";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public bool[] is_grab;

        public HanoiGrabMsg()
        {
            this.header = new Std.HeaderMsg();
            this.is_grab = new bool[3];
        }

        public HanoiGrabMsg(Std.HeaderMsg header, bool[] is_grab)
        {
            this.header = header;
            this.is_grab = is_grab;
        }

        public static HanoiGrabMsg Deserialize(MessageDeserializer deserializer) => new HanoiGrabMsg(deserializer);

        private HanoiGrabMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.is_grab, sizeof(bool), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.is_grab);
        }

        public override string ToString()
        {
            return "HanoiGrabMsg: " +
            "\nheader: " + header.ToString() +
            "\nis_grab: " + System.String.Join(", ", is_grab.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
