//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class HanoiPoseMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/HanoiPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg[] pose_array;

        public HanoiPoseMsg()
        {
            this.pose_array = new Geometry.PoseMsg[3];
        }

        public HanoiPoseMsg(Geometry.PoseMsg[] pose_array)
        {
            this.pose_array = pose_array;
        }

        public static HanoiPoseMsg Deserialize(MessageDeserializer deserializer) => new HanoiPoseMsg(deserializer);

        private HanoiPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pose_array, Geometry.PoseMsg.Deserialize, 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_array);
        }

        public override string ToString()
        {
            return "HanoiPoseMsg: " +
            "\npose_array: " + System.String.Join(", ", pose_array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
