//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class HanoiStatesMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/HanoiStates";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public bool[] is_grab;
        public Geometry.PoseMsg[] current_pose;
        public Geometry.PoseMsg[] static_pose;

        public HanoiStatesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.is_grab = new bool[3];
            this.current_pose = new Geometry.PoseMsg[3];
            this.static_pose = new Geometry.PoseMsg[3];
        }

        public HanoiStatesMsg(Std.HeaderMsg header, bool[] is_grab, Geometry.PoseMsg[] current_pose, Geometry.PoseMsg[] static_pose)
        {
            this.header = header;
            this.is_grab = is_grab;
            this.current_pose = current_pose;
            this.static_pose = static_pose;
        }

        public static HanoiStatesMsg Deserialize(MessageDeserializer deserializer) => new HanoiStatesMsg(deserializer);

        private HanoiStatesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.is_grab, sizeof(bool), 3);
            deserializer.Read(out this.current_pose, Geometry.PoseMsg.Deserialize, 3);
            deserializer.Read(out this.static_pose, Geometry.PoseMsg.Deserialize, 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.is_grab);
            serializer.Write(this.current_pose);
            serializer.Write(this.static_pose);
        }

        public override string ToString()
        {
            return "HanoiStatesMsg: " +
            "\nheader: " + header.ToString() +
            "\nis_grab: " + System.String.Join(", ", is_grab.ToList()) +
            "\ncurrent_pose: " + System.String.Join(", ", current_pose.ToList()) +
            "\nstatic_pose: " + System.String.Join(", ", static_pose.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
