//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class JointPosVelMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/JointPosVel";
        public override string RosMessageName => k_RosMessageName;

        public double[] positions;
        public double[] velocities;

        public JointPosVelMsg()
        {
            this.positions = new double[7];
            this.velocities = new double[7];
        }

        public JointPosVelMsg(double[] positions, double[] velocities)
        {
            this.positions = positions;
            this.velocities = velocities;
        }

        public static JointPosVelMsg Deserialize(MessageDeserializer deserializer) => new JointPosVelMsg(deserializer);

        private JointPosVelMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions, sizeof(double), 7);
            deserializer.Read(out this.velocities, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.positions);
            serializer.Write(this.velocities);
        }

        public override string ToString()
        {
            return "JointPosVelMsg: " +
            "\npositions: " + System.String.Join(", ", positions.ToList()) +
            "\nvelocities: " + System.String.Join(", ", velocities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
