//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class MarkerMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/Marker";
        public override string RosMessageName => k_RosMessageName;

        public uint frame_id;
        public uint marker_id;
        public string marker_name;
        public double x;
        public double y;
        public double z;
        public double size;
        public double residual;

        public MarkerMsg()
        {
            this.frame_id = 0;
            this.marker_id = 0;
            this.marker_name = "";
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.size = 0.0;
            this.residual = 0.0;
        }

        public MarkerMsg(uint frame_id, uint marker_id, string marker_name, double x, double y, double z, double size, double residual)
        {
            this.frame_id = frame_id;
            this.marker_id = marker_id;
            this.marker_name = marker_name;
            this.x = x;
            this.y = y;
            this.z = z;
            this.size = size;
            this.residual = residual;
        }

        public static MarkerMsg Deserialize(MessageDeserializer deserializer) => new MarkerMsg(deserializer);

        private MarkerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.marker_id);
            deserializer.Read(out this.marker_name);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.size);
            deserializer.Read(out this.residual);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.marker_id);
            serializer.Write(this.marker_name);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.size);
            serializer.Write(this.residual);
        }

        public override string ToString()
        {
            return "MarkerMsg: " +
            "\nframe_id: " + frame_id.ToString() +
            "\nmarker_id: " + marker_id.ToString() +
            "\nmarker_name: " + marker_name.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nsize: " + size.ToString() +
            "\nresidual: " + residual.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
