//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class ModeMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/Mode";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte MODE_UNKNOWN = -1;
        public const sbyte MODE_IDLE = 0;
        public const sbyte MODE_RT_JOINT_TORQUE = 1;
        public const sbyte MODE_RT_JOINT_POSITION = 2;
        public const sbyte MODE_NRT_JOINT_POSITION = 3;
        public const sbyte MODE_NRT_PLAN_EXECUTION = 4;
        public const sbyte MODE_NRT_PRIMITIVE_EXECUTION = 5;
        public const sbyte MODE_RT_CARTESIAN_MOTION_FORCE_BASE = 6;
        public const sbyte MODE_RT_CARTESIAN_MOTION_FORCE_TCP = 7;
        public const sbyte MODE_NRT_CARTESIAN_MOTION_FORCE_BASE = 8;
        public const sbyte MODE_NRT_CARTESIAN_MOTION_FORCE_TCP = 9;
        public sbyte mode;

        public ModeMsg()
        {
            this.mode = 0;
        }

        public ModeMsg(sbyte mode)
        {
            this.mode = mode;
        }

        public static ModeMsg Deserialize(MessageDeserializer deserializer) => new ModeMsg(deserializer);

        private ModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "ModeMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
