//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class RigidBodyMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/RigidBody";
        public override string RosMessageName => k_RosMessageName;

        public uint frame_id;
        public uint rigidbody_id;
        public string rigidbody_name;
        public double[] center_loc;

        public RigidBodyMsg()
        {
            this.frame_id = 0;
            this.rigidbody_id = 0;
            this.rigidbody_name = "";
            this.center_loc = new double[7];
        }

        public RigidBodyMsg(uint frame_id, uint rigidbody_id, string rigidbody_name, double[] center_loc)
        {
            this.frame_id = frame_id;
            this.rigidbody_id = rigidbody_id;
            this.rigidbody_name = rigidbody_name;
            this.center_loc = center_loc;
        }

        public static RigidBodyMsg Deserialize(MessageDeserializer deserializer) => new RigidBodyMsg(deserializer);

        private RigidBodyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.rigidbody_id);
            deserializer.Read(out this.rigidbody_name);
            deserializer.Read(out this.center_loc, sizeof(double), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.rigidbody_id);
            serializer.Write(this.rigidbody_name);
            serializer.Write(this.center_loc);
        }

        public override string ToString()
        {
            return "RigidBodyMsg: " +
            "\nframe_id: " + frame_id.ToString() +
            "\nrigidbody_id: " + rigidbody_id.ToString() +
            "\nrigidbody_name: " + rigidbody_name.ToString() +
            "\ncenter_loc: " + System.String.Join(", ", center_loc.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
