//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Flexiv
{
    [Serializable]
    public class RizonFrameMsg : Message
    {
        public const string k_RosMessageName = "flexiv_msgs/RizonFrame";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public FramePoseMsg[] frames;

        public RizonFrameMsg()
        {
            this.header = new Std.HeaderMsg();
            this.frames = new FramePoseMsg[0];
        }

        public RizonFrameMsg(Std.HeaderMsg header, FramePoseMsg[] frames)
        {
            this.header = header;
            this.frames = frames;
        }

        public static RizonFrameMsg Deserialize(MessageDeserializer deserializer) => new RizonFrameMsg(deserializer);

        private RizonFrameMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.frames, FramePoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.frames);
            serializer.Write(this.frames);
        }

        public override string ToString()
        {
            return "RizonFrameMsg: " +
            "\nheader: " + header.ToString() +
            "\nframes: " + System.String.Join(", ", frames.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
